TicketBookingOnline.Web/Areas/Admin/Controllers/VeController.cs
using Microsoft.AspNetCore.Mvc;
using TicketBookingOnline.ViewModels.Ves;
using TicketBookingOnline.Web.Areas.Admin.Controllers;
using TicketBookingOnline.Web.IServices;

namespace TicketBookingOnline.Web.Areas.CGV.Controllers
{
    [Area("Admin")]
    public class VeController : BaseController
    {
        private readonly IVeServices _veServices;

        public VeController(IVeServices veServices)
        {
            _veServices = veServices;
        }

        public async Task<IActionResult> Index(int? rapId, DateTime ? ngayChieu, string tenPhim, string userName, int index = 1)
        {
            var defaultDate = new DateTime(0001, 01, 01);
            if (ngayChieu == defaultDate)
                ngayChieu = null;
            int cumRapId = int.Parse(HttpContext.Session.GetString("CumRapId"));
            var ves = await _veServices.VeWithRowPerPage(cumRapId, rapId, ngayChieu, tenPhim, userName, 
                StaticDetails.VeAPIPath + "VeWithPerRowPage", index);
            int count  = await _veServices.CountTotalVe (cumRapId, rapId, ngayChieu, tenPhim, userName,
                StaticDetails.VeAPIPath + "CountTotalVe");
            ViewBag.Page = index;
            ViewBag.MaxPage = (count / 10) - (count % 10 == 0 ? 1 : 0);
            ViewBag.RapId = rapId;
           
            ViewBag.TenPhim = tenPhim;
            ViewBag.UserName = userName;
            
            if(ngayChieu != null)
            {
                ViewData["NgayChieu"] = ngayChieu.Value.ToString("yyyy'-'MM'-'dd");
            }
            else
            {
                ViewData["NgayChieu"] = "dd/mm/yyyy";
            }
            return View(ves);
        }

        public async Task<IActionResult> Details(int veId)
        {
            var ve = await _veServices.GetByIdAsync(veId, StaticDetails.VeAPIPath + "GetById");
            return View(ve);
        }

        public async Task<IActionResult> Confirm(int veId)
        {
            var response = await _veServices.ConfirmVeAsync(veId, StaticDetails.VeAPIPath + "ConfirmVe");
            if (response)
            {
                TempData["Success"] = "Xác nhận vé thành công !";
            }
            else
            {
                TempData["Error"] = "Đã xảy ra lỗi ...!";
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Cancel(int veId, string note)
        {
            var veVM = new DeleteVeViewModel();
            veVM.VeId= veId;
            veVM.Note= note;
            var response = await _veServices.CancelVeAsync(veVM, StaticDetails.VeAPIPath + "CancelVe");
            if (response)
            {
                TempData["Success"] = "Hủy vé thành công !";
            }
            else
            {
                TempData["Error"] = "Đã xảy ra lỗi ...!";
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

TicketBookingOnline.Web/Controllers/VeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketBookingOnline.Web.Controllers
{
    public class VeController : Controller
    {
        public IActionResult ChonGhe()
        {
            return View();
        }
    }
}

TicketBookingOnline.Web/Areas/Admin/Views/Ve/Details.cshtml
@model VeDetailViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "_AdminLayout";
}

<h1>Thông tin chi tiết vé</h1>
<hr />
<div>
    <div class="row">
        <p><b>Họ và tên khách hàng: </b>@Model.User.HoTen</p>
        <p><b>Số điện thoại: </b>@Model.User.SoDienThoai</p>
    </div>
    <div class="row">
        <input asp-for="VeId" class="form-control" hidden />
        <div class="col-4">
            <img src="~/posters/@Model.LichChieu.Phim.Anh" width=80% height=100% />
        </div>
        <div class="col-8">
            <h2>@Model.LichChieu.Phim.TenPhim</h2>
            <p><b>Thời lượng: </b>@Model.LichChieu.Phim.ThoiLuong phút</p>
            <p><b>Xuất chiếu: </b>@Model.LichChieu.XuatChieu</p>
            <p><b>Số lượng ghế: </b>@Model.SoLuongGheNgoi</p>
            <p><b>Loại ghế: </b>@Model.RapGhe.LoaiGhe.TenLoaiGhe</p>
            <p><b>Vị trí: </b>@Model.ViTri</p>
            <p><b>Khuyến mãi: @Model.LichChieu.PhanTramKM (%)</b></p>
            <h3><b style="color:red">Tổng giá vé: @String.Format("{0:0,0}", @Model.TongGiaVe) VNĐ</b></h3>
            
        </div>
    </div>
</div>
<br />
<div style="margin-top:20px">
    @if(DateTime.Now.Date == Model.LichChieu.XuatChieu.Date){
        <a asp-action="Confirm" asp-route-veId="@Model.VeId" class="btn btn-primary">Xác nhận</a>
    }
    <a asp-action="Index" class="btn btn-info">Trở về</a>
    <a href="" class="btn btn-danger" style="float:right" data-toggle="modal" data-target="#myModal"  
    onclick="document.getElementById('veId').value=@Model.VeId" >Hủy vé</a>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <form asp-action="Cancel" method="post">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-body">
                    <h4 class="modal-title" style="float: left">Xác nhận hủy vé</h4>
                    <button type="button" style="float: right" class="close" data-dismiss="modal">&times;</button>
                    <hr />
                    <input name="veId" id="veId" hidden />
                    <div class="form-group">
                        <label class="form-label">Lý do hủy:</label>
                        <input type="text" class="form-control" name="note" id="note" required/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                    <input type="submit" value="Hủy vé" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>

TicketBookingOnline.Web/Areas/Admin/Views/Ve/Index.cshtml
@model IEnumerable<VeViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "_AdminLayout";
    var ngayChieu =  ViewData["NgayChieu"] as string;
    var nextPage = (int)ViewBag.Page + 1;
    var prevPage = (int)ViewBag.Page - 1 < 0 ? 1 : (int)ViewBag.Page - 1;
    var disableNext = "disable";
    if(Model != null)
    {
        disableNext = Model.ToList().Count() < 10 ? "disable" : "";
    }    
    var disablePrev = (int)ViewBag.Page == 1 ? "disable" : "";
}

<h1>Danh sách vé mới</h1>
<hr />
@if (Model == null)
{
    <h1>Không có vé nào được đặt</h1>
}
else
{
    <form asp-action="Index" method="post" style="margin-top:10px; margin-right:20%">
        <div class="row">

            <div class="col-6">
                <input id="tenPhim" name="tenPhim" class="form-control" placeholder="Nhập tên phim ..." style="width:60%" />
                <br>
                <input id="userName" name="userName" class="form-control" placeholder="Nhập tên khách hàng ..." style="width:60%" />
            </div>
            <div class="col-6">
                <input id="ngayChieu" name="ngayChieu" type="date" class="form-control" style="width:60%; float:right" value="@ngayChieu"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Tìm kiếm" class="btn btn-info" style="float:right" />
            </div>
        </div>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.User.HoTen)
                </th>
                <th width=25%>
                    @Html.DisplayNameFor(model => model.LichChieu.Phim.TenPhim)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LichChieu.XuatChieu)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SoLuongGheNgoi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TongGiaVe)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.HoTen)
                    </td>
                    <td width=25%>
                        @Html.DisplayFor(modelItem => item.LichChieu.Phim.TenPhim)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LichChieu.XuatChieu)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SoLuongGheNgoi)
                    </td>
                    <td>
                        @{
                            string tongGiaVe = @String.Format("{0:0,0}", @item.TongGiaVe);
                        }
                        @Html.DisplayFor(modelItem => tongGiaVe)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-veId="@item.VeId">Chi tiết</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<div class="btn-toolbar justify-content-center" role="toolbar" aria-label="Toolbar with button groups">
     <div class="btn-group mr-2" role="group" aria-label="First group">
         <a class="prev @disablePrev btn btn-white btn-white-group" style="border:0.6px solid green" 
         asp-controller="Ve" asp-action="Index" asp-route-rapId="@ViewBag.RapId"
         asp-route-ngayChieu="@ViewBag.NgayChieu" asp-route-tenPhim="@ViewBag.TenPhim"
         asp-route-userName="@ViewBag.UserName" asp-route-index="@prevPage">&laquo;</a>

     </div>
     <div class="btn-group mr-2" role="group" aria-label="Second group">
         @for (int i = 1; i <= ViewBag.MaxPage + 1; i++)
         {
            if(@ViewBag.Page == i)
            {
                <a class="btn btn-white mr-2 btn-white-group activePage" style="border:0.6px solid green" 
                 asp-controller="Ve" asp-action="Index" asp-route-rapId="@ViewBag.RapId"
                 asp-route-ngayChieu="@ViewBag.NgayChieu" asp-route-tenPhim="@ViewBag.TenPhim"
                 asp-route-userName="@ViewBag.UserName" asp-route-index="@i">@i </a>
            }
            else
            {
                <a class="btn btn-white mr-2 btn-white-group" style="border:0.6px solid green" 
                 asp-controller="Ve" asp-action="Index" asp-route-rapId="@ViewBag.RapId"
                 asp-route-ngayChieu="@ViewBag.NgayChieu" asp-route-tenPhim="@ViewBag.TenPhim"
                 asp-route-userName="@ViewBag.UserName" asp-route-index="@i">@i </a>               
            }
         }
     </div>
     <div class="btn-group" role="group" aria-label="Third group">
         <a class="next @disableNext btn btn-white btn-white-group" style="border:0.6px solid green" 
         asp-controller="Ve" asp-action="Index" asp-route-rapId="@ViewBag.RapId"
         asp-route-ngayChieu="@ViewBag.NgayChieu" asp-route-tenPhim="@ViewBag.TenPhim"
         asp-route-userName="@ViewBag.UserName" asp-route-index="@nextPage">&raquo;</a>
     </div>
 </div>